---
name: E2E Tests
on:
  pull_request:
jobs:
  e2e-test:
    if: ${{ github.event.label.name == 'state:needs_test' }}
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout tower-qa
      - uses: actions/checkout@v2
        with:
          path: tower-qa

      - name: Log in to gcr.io
        run: |
          echo "${{ secrets.GCR_PULL_SECRET }}" | docker login gcr.io -u _json_key --password-stdin

      - name: Pull awx_cypress_base image
        run: |
          docker pull gcr.io/ansible-tower-engineering/awx_cypress_base:stable

      - name: Build cypress
        run: |
          cd tower-qa/ui-tests/awx-pf-tests
          docker build -t awx-pf-tests . 

      - name: Log in to registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Pre-pull image to warm build cache
        run: |
          docker pull ghcr.io/${{ github.repository_owner }}/awx_devel:${{ github.base_ref }}

      - name: Build image
        run: |
          DEV_DOCKER_TAG_BASE=ghcr.io/${{ github.repository_owner }} COMPOSE_TAG=${{ github.base_ref }} make docker-compose-build